# Generated by Django 5.1.3 on 2024-12-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notconfirmedusers',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='notconfirmedusers',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='notconfirmedusers',
            name='department',
        ),
        migrations.RemoveField(
            model_name='users',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='users',
            name='department',
        ),
        migrations.AddField(
            model_name='notconfirmedusers',
            name='last_name',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notconfirmedusers',
            name='email',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.TextField(max_length=150),
        ),
    ]
